import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart'; 

Future<void> generateFullReportPdf({
  required List entries,
  required String month,
  required String customerName,
}) async {
  final pdf = pw.Document();

  double totalMilk = 0.0;
  double totalAmount = 0;
  double totalReceived = 0;
  double totalPaid = 0;
  double lastBalance = 0;
  double totalFatSum = 0.0;
  int fatEntryCount = 0;

  for (var e in entries) {
    totalMilk += e.liters;
    totalAmount += e.amount;
    totalReceived += e.recived;
    totalPaid += e.paid;
    if (e.fat > 0) {
      totalFatSum += e.fat;
      fatEntryCount++;
    }
    
  }
  double averageFat = fatEntryCount > 0 ? totalFatSum / fatEntryCount : 0.0;

  if (entries.isNotEmpty) {
    lastBalance = entries.last.balance;
  }

  // Cover page
  pdf.addPage(
    pw.Page(
      build: (context) => pw.Center(
        child: pw.Column(
          mainAxisAlignment: pw.MainAxisAlignment.center,
          children: [
          
            pw.Text(
              "MILKDY",
              style: pw.TextStyle(
                fontSize: 32,
                fontWeight: pw.FontWeight.bold,
              ),
            ),

            pw.SizedBox(height: 10),

            pw.Text("Milk Report",
                style: pw.TextStyle(fontSize: 18)),

            pw.SizedBox(height: 20),

            pw.Text("Customer: $customerName"),
            pw.Text("Month: $month"),

            pw.SizedBox(height: 40),

            pw.Text(
              "Generated by Milkdy App",
              style: pw.TextStyle(fontSize: 10),
            ),
          ],
        ),
      ),
    ),
  );
 
  // REPORT PAGE
  pdf.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      build: (context) => [

        // HEADER
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text("Milkdy Report",
                style: pw.TextStyle(
                    fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Text(month),
          ],
        ),

        pw.SizedBox(height: 10),
        pw.Text("Customer: $customerName".toUpperCase()),
        pw.Divider(),

        pw.SizedBox(height: 10),

        /// TABLE
        pw.Table(
          border: pw.TableBorder.all(width: 0.5),
          children: [

            /// HEADER
            pw.TableRow(
              decoration: pw.BoxDecoration(color: PdfColors.grey300),
              children: [
                _cell("Date"),
                _cell("Milk"),
                _cell("Fat"),
                _cell("Rate"),
                _cell("Amount"),
                _cell("Rec"),
                _cell("Paid"),
                _cell('Feed'),
                _cell("Balance"),
              ],
            ),

            /// DATA
            ...entries.map((e) {
              return pw.TableRow(
                children: [
                  _cell("${e.date.day}/${e.date.month}"),
                  _cell("${e.liters}"),
                  _cell("${e.fat}"),
                  _cell("${e.rate}"),
                  _cell("${e.amount}"),
                  _cell("${e.recived}"),
                  _cell("${e.paid}"),
                  _cell('${e.feed}'),
                  _cell("${e.balance}"),
                ],
              );
            }).toList(),

            /// TOTAL
            pw.TableRow(
              decoration: pw.BoxDecoration(color: PdfColors.grey200),
              children: [
                _cell("TOTAL", bold: true),
                _cell(totalMilk.toStringAsFixed(2), bold: true),
                _cell(averageFat.toStringAsFixed(2), bold: true),
                _cell("-"),
                _cell(totalAmount.toStringAsFixed(0), bold: true),
                _cell(totalReceived.toStringAsFixed(0), bold: true),
                _cell(totalPaid.toStringAsFixed(0), bold: true),
                _cell('_'),
                _cell(lastBalance.toStringAsFixed(0), bold: true),
              ],
            ),
          ],
        ),

        pw.SizedBox(height: 20),

        /// FOOTER
        pw.Align(
          alignment: pw.Alignment.centerRight,
          child: pw.Text(
            "Generated on: ${DateTime.now()}",
            style: pw.TextStyle(fontSize: 10),
          ),
        ),
      ],
    ),
  );

  // SHARE
  await Printing.layoutPdf(
    onLayout: (format) async => pdf.save(),
  );
/// save
  final directory = await getApplicationDocumentsDirectory();
  final filePath = "${directory.path}/Milkdy_$month.pdf";
  final file = File(filePath);
  
  // Save the PDF bytes 
  await file.writeAsBytes(await pdf.save());

  // SHARE TO WHATSAPP
  await Share.shareXFiles(
    [XFile(filePath)],
    text: 'Milk Report for $customerName - $month',
  );
}
pw.Widget _cell(String text, {bool bold = false}) {
  return pw.Padding(
    padding: const pw.EdgeInsets.all(5),
    child: pw.Text(
      text,
      style: pw.TextStyle(
        fontSize: 10,
        fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
      ),
    ),
  );
}